import { ObservabilitySnapshot } from "./types.js";

/**
 * Generates realistic mock telemetry snapshot for local UI development and testing.
 */
export function generateMockSnapshot(serviceName = "bookme-api"): ObservabilitySnapshot {
  const now = Date.now();
  return {
    service: {
      name: serviceName,
      environment: "production",
      version: "1.2.4",
      uptimeSeconds: 345600, // 4 days
      timestamp: now,
    },
    summary: {
      totalRequests: 42421,
      activeRequests: 14,
      errorRate: 0.31,
      p50LatencyMs: 71,
      p95LatencyMs: 183,
      p99LatencyMs: 421,
      avgLatencyMs: 84.5,
    },
    windows: {
      last1m: { totalRequests: 10, errorRequests: 1, errorRate: 0.10, avgDurationMs: 52.0 },
      last5m: { totalRequests: 320, errorRequests: 1, errorRate: 0.31, avgDurationMs: 81.2 },
      last15m: { totalRequests: 950, errorRequests: 4, errorRate: 0.42, avgDurationMs: 82.5 },
      last30m: { totalRequests: 1980, errorRequests: 7, errorRate: 0.35, avgDurationMs: 84.0 },
      last1h: { totalRequests: 4120, errorRequests: 15, errorRate: 0.36, avgDurationMs: 84.5 },
      last2h: { totalRequests: 8200, errorRequests: 28, errorRate: 0.34, avgDurationMs: 85.1 },
      last24h: { totalRequests: 42421, errorRequests: 132, errorRate: 0.31, avgDurationMs: 84.5 },
      last7d: { totalRequests: 42421, errorRequests: 132, errorRate: 0.31, avgDurationMs: 78.0 },
      last30d: { totalRequests: 42421, errorRequests: 132, errorRate: 0.31, avgDurationMs: 80.0 },
    },
    http: {
      statusBreakdown: {
        status2xx: 40724,
        status3xx: 1272,
        status4xx: 382,
        status5xx: 43,
      },
      topEndpoints: [
        {
          method: "GET",
          route: "/api/users",
          requests: 14210,
          avgDurationMs: 62.4,
          p95DurationMs: 120.5,
          errorCount: 12,
        },
        {
          method: "POST",
          route: "/api/login",
          requests: 9840,
          avgDurationMs: 114.2,
          p95DurationMs: 240.0,
          errorCount: 65,
        },
        {
          method: "GET",
          route: "/api/products",
          requests: 7420,
          avgDurationMs: 78.1,
          p95DurationMs: 155.0,
          errorCount: 8,
        },
        {
          method: "POST",
          route: "/api/orders",
          requests: 4310,
          avgDurationMs: 189.5,
          p95DurationMs: 380.2,
          errorCount: 24,
        },
        {
          method: "GET",
          route: "/api/notifications",
          requests: 3920,
          avgDurationMs: 45.0,
          p95DurationMs: 82.0,
          errorCount: 4,
        },
        {
          method: "DELETE",
          route: "/api/sessions",
          requests: 2721,
          avgDurationMs: 51.3,
          p95DurationMs: 95.0,
          errorCount: 2,
        },
      ],
    },
    runtime: {
      cpuPercent: 32.4,
      memoryRssMb: 412.5,
      heapUsedMb: 183.2,
      heapTotalMb: 245.0,
      eventLoopLagMs: 1.4,
      nodeVersion: "v20.12.0",
    },
    recentErrors: [
      {
        id: "err-mock-1",
        timestamp: Date.now() - 1000 * 60 * 2,
        message: "PaymentGatewayTimeoutException: Stripe upstream gateway timed out after 5000ms",
        stack: "Error: Stripe upstream gateway timed out\n    at PaymentClient.processCharge (/app/services/payment.js:42:15)\n    at async /app/routes/orders.js:88:9",
        route: "/api/orders",
        method: "POST",
        statusCode: 504,
        service: serviceName,
        fingerprint: "504-/api/orders-PaymentGatewayTimeoutException",
        occurrences: 8,
        firstSeen: Date.now() - 1000 * 60 * 45,
        lastSeen: Date.now() - 1000 * 60 * 2,
        breadcrumbs: [
          { timestamp: Date.now() - 1000 * 120, category: "http", message: "POST /api/orders received from client", level: "info" },
          { timestamp: Date.now() - 1000 * 118, category: "auth", message: "JWT token verified for user_id: usr_9942", level: "info" },
          { timestamp: Date.now() - 1000 * 115, category: "db", message: "SELECT * FROM inventory WHERE item_id = $1 (took 3.2ms)", level: "info" },
          { timestamp: Date.now() - 1000 * 110, category: "http", message: "POST https://api.stripe.com/v1/charges -> pending", level: "info" },
          { timestamp: Date.now() - 1000 * 105, category: "log", message: "Gateway socket did not reply within timeout threshold", level: "warn" },
        ],
        context: {
          os: "linux (x64)",
          nodeVersion: "v20.12.0",
          memoryMb: 183,
          headers: {
            "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)",
            "host": "api.myapp.com",
            "content-type": "application/json",
          },
          query: {},
          ip: "192.168.1.104",
        },
      },
      {
        id: "err-mock-2",
        timestamp: Date.now() - 1000 * 60 * 8,
        message: "DatabaseConnectionPoolExhausted: Pool max connections (20) reached",
        stack: "Error: Pool max connections (20) reached\n    at Pool.acquire (/app/db/pool.js:105:22)\n    at async getUserProfile (/app/models/user.js:31:18)",
        route: "/api/users",
        method: "GET",
        statusCode: 500,
        service: serviceName,
        fingerprint: "500-/api/users-DatabaseConnectionPoolExhausted",
        occurrences: 34,
        firstSeen: Date.now() - 1000 * 60 * 120,
        lastSeen: Date.now() - 1000 * 60 * 8,
        breadcrumbs: [
          { timestamp: Date.now() - 1000 * 490, category: "http", message: "GET /api/users received", level: "info" },
          { timestamp: Date.now() - 1000 * 485, category: "db", message: "Acquiring client from Postgres connection pool...", level: "info" },
          { timestamp: Date.now() - 1000 * 480, category: "log", message: "Pool connection timeout: all 20 connections in use", level: "error" },
        ],
        context: {
          os: "linux (x64)",
          nodeVersion: "v20.12.0",
          memoryMb: 195,
        },
      },
      {
        id: "err-mock-3",
        timestamp: Date.now() - 1000 * 45,
        message: "InternalServerError (500): Render timeout while hydrating /admin/observability",
        stack: "Error: Render timeout while hydrating /admin/observability\n    at ObservabilityConsole.render (/app/admin/observability/page.tsx:42:11)\n    at processRequest (/node_modules/next/server.js:184:22)",
        route: "/admin/observability",
        method: "GET",
        statusCode: 500,
        service: serviceName,
        fingerprint: "500-/admin/observability-RenderTimeout",
        occurrences: 2,
        firstSeen: Date.now() - 1000 * 60 * 5,
        lastSeen: Date.now() - 1000 * 45,
        breadcrumbs: [
          { timestamp: Date.now() - 1000 * 120, category: "http", message: "GET /admin/observability -> 200 (18.4ms)", level: "info" },
          { timestamp: Date.now() - 1000 * 75, category: "http", message: "GET /admin/observability -> 500 in 2021ms", level: "error" },
          { timestamp: Date.now() - 1000 * 45, category: "http", message: "GET /admin/observability -> 500 in 415ms", level: "error" },
        ],
        context: {
          os: "linux (x64)",
          nodeVersion: "v20.12.0",
          memoryMb: 245,
          headers: {
            "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64)",
            "host": "localhost:3000",
          },
          query: {},
          ip: "127.0.0.1",
        },
      },
    ],
    breadcrumbs: [
      { timestamp: Date.now() - 1000 * 75, category: "http", message: "GET /admin/observability -> 500 in 2021ms", level: "error" },
      { timestamp: Date.now() - 1000 * 45, category: "http", message: "GET /admin/observability -> 500 in 415ms", level: "error" },
      { timestamp: Date.now() - 1000 * 30, category: "http", message: "GET /api/users -> 200 (14.2ms)", level: "info" },
      { timestamp: Date.now() - 1000 * 20, category: "auth", message: "JWT token verified for user_id: usr_9942", level: "info" },
      { timestamp: Date.now() - 1000 * 15, category: "db", message: "SELECT * FROM products WHERE active = true (took 2.4ms)", level: "info" },
      { timestamp: Date.now() - 1000 * 5, category: "http", message: "POST /api/orders -> 504 (48.1ms)", level: "error" },
    ],
    dbCrashLogs: [
      {
        id: "crash-db-101",
        timestamp: Date.now() - 1000 * 60 * 14,
        message: "PostgreSQLError (500): Deadlock detected on table 'orders' while executing concurrent transaction",
        stack: "Error: Deadlock detected on table 'orders'\n    at Query.run (/app/node_modules/pg/lib/query.js:84:14)\n    at async completeOrderTransaction (/app/services/checkout.service.js:122:10)",
        route: "/api/orders/checkout",
        method: "POST",
        statusCode: 500,
        service: serviceName,
        fingerprint: "500-/api/orders/checkout-DeadlockDetected",
        occurrences: 4,
        firstSeen: Date.now() - 1000 * 60 * 45,
        lastSeen: Date.now() - 1000 * 60 * 14,
        breadcrumbs: [
          { timestamp: Date.now() - 1000 * 60 * 15, category: "auth", message: "User session auth verified (usr_381)", level: "info" },
          { timestamp: Date.now() - 1000 * 60 * 14.5, category: "db", message: "BEGIN TRANSACTION ISOLATION LEVEL SERIALIZABLE", level: "info" },
          { timestamp: Date.now() - 1000 * 60 * 14, category: "db", message: "Deadlock detected: Process 4124 awaits ShareLock on relation 16402", level: "error" },
        ],
        context: {
          os: "linux (x64)",
          nodeVersion: "v22.2.0",
          memoryMb: 312,
          headers: {
            "user-agent": "Mozilla/5.0 (iPhone; CPU iPhone OS 17_5 like Mac OS X)",
            "host": "api.production.internal",
          },
        },
      },
      {
        id: "crash-db-102",
        timestamp: Date.now() - 1000 * 60 * 42,
        message: "GatewayTimeout (504): Upstream Payment Gateway HTTP 504 after 30000ms timeout",
        stack: "Error: GatewayTimeout: Payment Gateway unreachable\n    at PaymentClient.charge (/app/integrations/payment.js:87:12)\n    at async processPayment (/app/controllers/payment.controller.js:45:9)",
        route: "/api/payments/charge",
        method: "POST",
        statusCode: 504,
        service: serviceName,
        fingerprint: "504-/api/payments/charge-GatewayTimeout",
        occurrences: 1,
        firstSeen: Date.now() - 1000 * 60 * 42,
        lastSeen: Date.now() - 1000 * 60 * 42,
        breadcrumbs: [
          { timestamp: Date.now() - 1000 * 60 * 43, category: "http", message: "POST https://api.stripe.com/v1/charges sent", level: "info" },
          { timestamp: Date.now() - 1000 * 60 * 42, category: "http", message: "Gateway timed out after 30.0s", level: "error" },
        ],
        context: {
          os: "linux (x64)",
          nodeVersion: "v22.2.0",
          memoryMb: 285,
        },
      },
      {
        id: "crash-db-103",
        timestamp: Date.now() - 1000 * 60 * 115,
        message: "ServiceUnavailable (503): Redis cache connection broken: ECONNRESET",
        stack: "Error: Redis connection broken: ECONNRESET\n    at RedisClient.onClose (/app/node_modules/ioredis/lib/redis.js:412:15)\n    at emitCloseNT (node:net:135:8)",
        route: "/api/inventory/sync",
        method: "GET",
        statusCode: 503,
        service: serviceName,
        fingerprint: "503-/api/inventory/sync-RedisConnReset",
        occurrences: 8,
        firstSeen: Date.now() - 1000 * 60 * 180,
        lastSeen: Date.now() - 1000 * 60 * 115,
        breadcrumbs: [
          { timestamp: Date.now() - 1000 * 60 * 116, category: "db", message: "GET inventory:item:4921", level: "info" },
          { timestamp: Date.now() - 1000 * 60 * 115, category: "db", message: "Redis stream disconnected abruptly", level: "error" },
        ],
        context: {
          os: "linux (x64)",
          nodeVersion: "v22.2.0",
          memoryMb: 198,
        },
      },
    ],
  };
}
